language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "kiwibis-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: kiwibis # see README
  api_key:
    secure: yBYQAdl+AabpAjkfyzw9IauLgqLNdqFQZfdzmSlx0ViytKNjqLHl5Ij7EI1QOJtW7SnDM/MZsBnm1aVHd7WHk+2jdDFYaiOad27D50zrSIKy5orSlF3tymXM7XYhN64QGoJbK1U0gl6Lo1/1das3sxT6P5aEC2ufnrC1zo7QsaatWJ7L4cIMbaDudfQBIki9yvqPztlR0/BOMM617YQi13plEu5fLAGDhlmDzGm/eIsjcU9biHl8tcTd330FjScFQRzss8izGGVdJy+RpyF9fL8sVdHRwP5t43FoAZuhPwmJCQbkl/zqBSb1etwk+8+doJoKAXWQvYlrFxYhIE83eQfjUwnGk5DxXu6HBhUq5KbxSnCt3Xs13U8aXXOYkm0MorS8nJgQs2eFe4KyjXf57rbCB9/UdHRBs/LLrYY/BvHP+hJlGC2brdDEuOR7JF3u1L/yOjgWB227X0UV1m0+nbla2afuR17TkCAvoOC5d42GpQ9qGmUodOOh+wDGsqgEATAVCaWHF0N9RpG6SIW79S6+ThQ6Rp+bjEFjuN6Xznquv+BEl8/Z6D1vZb8uMsdUT3W6uoVGt6+maNIDMq2F0MmYPyaXlVMqkxiVANgrJdN/rM4OQxZsiBNe2KNHy6DhE02Ikz6a0mjSiBRpwAvoCl+5kzX39y4jv+X4PnFhuRU= # see README
